config/routes.rb
Rails.application.routes.draw do

	root "stillinger#index"
	
	get "soeknader" => "soeknader#index", as: :soeknader
	

end

app/models/soeknad.rb
class Soeknad < ActiveRecord::Base
	belongs_to :stilling
end

app/models/stilling.rb
class Stilling < ActiveRecord::Base
	has_many :soeknads
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stillinger_controller.rb
class StillingerController < ApplicationController
	def index
		@stillinger = Stilling.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stillinger_helper.rb
module StillingerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lærlingbanken</title>
  
  <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,500,700' rel='stylesheet' type='text/css'>
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse">
	  <div class="container">
	    <div class="row">
	      <div id="logo-container" class="col-xs-2 hidden-xs"><div><img src="https://photos-1.dropbox.com/t/2/AAAztGH9dzOAR6MLZb_5-ZY3q8oeJmDQl91NYco5E7PjJA/12/416282756/png/32x32/1/_/1/2/logo.png/ELyKhqsDGAkgAigC/OmhqBO_UYeH5-SSLgnoYYioYZQY9CggxUZu0dCXbuC0?size=1024x768&size_mode=3"></div></div>
	      <div class="col-sm-8 col-xs-11 text-center" id="tittel">
	        <h1>Lærlingbanken</h1>
          </div>
        </div>
      </div>
</div>

<%= yield %>

</body>
</html>

app/views/stillinger/index.html.erb
<div class="container row">
	<!--Buffer-->
	<div class="col-sm-1 col-md-2 hidden-xs"></div>
	
	<!-- Container med alt innhold -->		
	<div class="innhold col-xs-12 col-sm-10 col-md-8">
		<div class="row">
		
			<div class="soekeboks row">
				<span>
					<input placeholder="Søk i stillinger" class="form-control" />
				</span>
			</div>
				
				<!-- Knappene -->
			<div id="filter" "class="row"
			
				<!-- buffer -->
				<div class="col-xs-1 hidden-sm hidden-md hidden-lg"></div>
				
				<ul class="nav nav-pills filter">
					<li id="filter"class="col-xs-5 col-sm-3 col-md-2 text-center"><h4>Filter</h4></li>
					<li id="favoritt" class="col-xs-5 col-sm-3 col-md-2 text-center"><h4>Favoritter</h4></li>
				</ul>
			</div>
				
		  <!--Animert meny under--> 
			<div class="row filterMeny">
			</div>
		</div>
  <!-- Feed -->

  <!-- Looper igjennom et "card" av gangen -->
	
		<% @stillinger.each do |stilling| %>
		<div class="card row">
			<div class="left-side media-left">
			  <img src="<%= stilling.logo %>">
			  <p> <%= stilling.avstand %> </p> <br>
			</div>
			
			<div class="middle media-body">
				
				<h1> 
					<%= stilling.stilling_navn %> 
					<small> <%= stilling.bedrift_nettside %> </small>
				</h1>
					   
				
				<div>
					<p> 
						<%= stilling.yrke %>. 
						Stillingen krever <%= stilling.krav_utdanning %>
					</p>
				</div>
		  
				<div class="beskrivelse">
					<p> <%= stilling.beskrivelse %> </p>
					<%= link_to "Vis mer", soeknader_path %>
				</div>
			</div>
			<p class="dato pull-right">Søknadsfrist: <%= stilling.frist %></p>
		</div>
		<% end %>
	</div> 
	
	<!--Buffer-->
	<div class="col-sm-1 col-md-2 hidden-xs"></div>
	
</div>